'use client';

import React from 'react';
import AppShell from '@/components/AppShell';
import StatusBadge from '@/components/StatusBadge';
import { useApp } from '@/lib/app-context';
import { Box, Download, FileJson, FileText, Clock } from 'lucide-react';

export default function ArtifactsPage() {
  const { artifacts } = useApp();

  return (
    <AppShell breadcrumbs={[{ label: 'Artifacts' }]}>
      <div style={{ padding: '32px' }}>
        <div style={{ marginBottom: 24 }}>
          <h1 style={{ fontSize: 32, fontFamily: 'var(--font-serif)', marginBottom: 4 }}>Artifacts</h1>
          <p style={{ color: 'var(--color-text-tertiary)', fontSize: 14 }}>
            Browse all structured data generated by your AI execution pipelines.
          </p>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 16 }}>
          {artifacts.map((art: any) => {
            const filename = art.relativePath.split('/').pop() || art.id;
            return (
              <div key={art.id} className="card card-interactive" style={{ padding: 20 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 }}>
                  <div style={{
                    width: 40, height: 40, borderRadius: 'var(--radius-md)',
                    backgroundColor: 'var(--color-primary-soft)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    color: 'var(--color-primary)',
                  }}>
                    {art.artifactType === 'JSON' ? <FileJson size={20} /> : <FileText size={20} />}
                  </div>
                  {art.isLatest && <span className="badge badge-success" style={{ textTransform: 'none', letterSpacing: 0, fontSize: 10 }}>Latest</span>}
                </div>
                <h3 style={{ fontSize: 15, fontWeight: 600, fontFamily: 'var(--font-sans)', marginBottom: 4 }}>{filename}</h3>
                <p style={{ fontSize: 12, color: 'var(--color-text-tertiary)', marginBottom: 12 }}>{art.summary || 'No summary'}</p>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingTop: 12, borderTop: '1px solid var(--color-border-soft)' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <span style={{ fontSize: 11, color: 'var(--color-text-muted)', fontFamily: 'var(--font-mono)' }}>{art.version}</span>
                    <span style={{ fontSize: 11, color: 'var(--color-text-muted)' }}>· {art.skillName}</span>
                  </div>
                  {art.verdict && <StatusBadge status={art.verdict === 'PASS' ? 'success' : art.verdict === 'FAIL' ? 'error' : 'warning'} label={art.verdict} />}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </AppShell>
  );
}
