import type { JsonObject } from "@dstack/shared";

export const defaultOutputs: Record<string, JsonObject> = {
  "office-hours": { projectName: "Untitled Project", summary: "", targetUsers: [], coreProblem: "", successMetrics: [], techStack: { frontend: "", backend: "", infra: "" }, constraints: [], outOfScope: [], openQuestions: [] },
  autoplan: { planVersion: "1", generatedAt: new Date().toISOString(), phases: [], openDecisions: [], riskFlags: ["Plan requires review."], assumptionsMade: [] },
  "plan-ceo-review": { overallVerdict: "REVISE", phaseReviews: [], globalConcerns: [], mustFixBeforeProceeding: [], approvedAspects: [] },
  "plan-eng-review": { overallVerdict: "REVISE", taskReviews: [], architectureConcerns: [], missingInfrastructure: [], securityFlags: [], testingGaps: [], mustFixBeforeProceeding: [] },
  "design-consultation": { screens: [], userFlows: [], designPrinciples: [], responsiveStrategy: "", openDesignDecisions: [] },
  "design-review": { overallVerdict: "REVISE", screenReviews: [], uxAntiPatterns: [], accessibilityFailures: [], mustFixBeforeProceeding: [] },
  review: { reviewedFiles: [], fileReviews: [], overallVerdict: "PASS", summary: "No review findings.", criticalIssues: [] },
  qa: { passedChecks: [], failedChecks: [], testResults: { passed: 0, failed: 0, skipped: 0, testCommand: "" }, browserFindings: [], overallVerdict: "PASS", blockers: [], recommendations: [] },
  "qa-only": { testCommand: "", passed: 0, failed: 0, skipped: 0, failures: [], overallVerdict: "PASS" },
  investigate: { issue: "", rootCause: "", confidence: "low", relevantFiles: [], executionTrace: [], proposedFix: { description: "", affectedFiles: [], approach: "" }, alternativeHypotheses: [] },
  ship: { shippable: false, gateResults: [], blockers: [], changelogEntry: "", suggestedTag: "", deployCommand: "", deployedAt: null },
  "context-save": { name: "fake", savedAt: "", gitHead: "", branch: "", artifactPointers: {}, summary: "" },
  "context-restore": { checkpointName: "fake", restoredAt: "", artifactsRestored: [], gitHeadAtSave: "", note: "" },
  browse: { url: "", title: "", summary: "", consoleErrors: [], networkErrors: [], accessibilityIssues: [], interactiveElements: [], screenshotPath: "", recommendations: [] },
  "plan-design-review": { overallVerdict: "REVISE", planDesignGaps: ["Define screen-level design deliverables."], accessibilityFlags: ["Add accessibility acceptance criteria."], sequencingIssues: [], undefinedDeliverables: [], phaseReviews: [], mustFixBeforeProceeding: ["Add design specification task."] },
  "plan-devex-review": { overallVerdict: "REVISE", missingDevexTasks: ["Document local setup."], setupComplexityScore: 3, setupComplexityRationale: "Moderate setup complexity.", onboardingGaps: [], toolingIssues: [], testInfraGaps: ["Document tests."], ciCdGaps: ["Add CI check."], documentationGaps: [], phaseReviews: [], mustFixBeforeProceeding: [] },
  "devex-review": { overallScore: 62, overallVerdict: "REVISE", categories: [], readmeScore: 12, readmeGaps: ["Clarify first-run setup."], envSetupScore: 10, envSetupGaps: ["Document env vars.", "Document fake provider."], testRunTime: null, criticalIssues: [], mustFixBeforeProceeding: [] },
  "design-shotgun": { subject: "Primary workflow", variants: [], recommendation: "Card Explorer", decisionCriteria: [] },
  "design-html": { screenName: "Primary workflow", variantName: null, htmlFilePath: "", componentsCovered: [], accessibilityNotes: [], knownLimitations: [], viewInstructions: "" },
  "landing-report": { url: "", analyzedAt: "", desktopScreenshotPath: "", mobileScreenshotPath: "", performanceMetrics: {}, performanceVerdict: "WARN", aboveFoldAnalysis: {}, mobileAnalysis: {}, copyIssues: [], accessibilityIssues: [], brokenLinks: [], consoleErrors: [], networkErrors: [], overallScore: 71, overallVerdict: "WARN", topRecommendations: [], scoreFormula: "" },
  "setup-deploy": { platform: "custom", environment: "staging", deployCommand: "echo dstack deploy", dryRunCommand: "echo dstack deploy dry-run", healthCheckUrl: null, rollbackCommand: null, requiredEnvVars: [], deployConfigPath: ".dstack/deploy.json", dryRunResult: "PASS", dryRunOutput: "", warnings: [] },
  "land-and-deploy": { environment: "staging", deployedAt: "", deployCommand: "", deployOutput: "", exitCode: 0, deployVerdict: "PASS", healthCheckUrl: null, healthCheckVerdict: "SKIPPED", healthCheckAttempts: 0, rollbackRequired: false, rollbackExecuted: false, rollbackOutput: null, gitHead: "unknown", gitBranch: "unknown", blockers: [] },
  "setup-browser-cookies": { sessionName: "default", targetUrl: "", cookieCount: 0, sessionFilePath: "", authenticationVerified: true, authIndicatorsFound: [], expiresAt: null, warnings: [] },
  scrape: { requestedUrls: [], scrapedUrls: [], skippedUrls: [], robotsRespected: true, data: [], dataFilePath: "", warnings: [] },
  "pair-agent": { task: "", sessionName: null, plannedSteps: [], executedSteps: [], stepsCompleted: 0, stepsPlanned: 0, taskVerdict: "COMPLETE", checkpointsPassed: 0, auditLogPath: "" },
  health: { healthScore: 68, healthVerdict: "DEGRADED", computedAt: "", staleArtifacts: [], openGates: [], neverRunSkills: [], dependencyAudit: {}, gitHealth: {}, topRecommendations: [], summary: "", scoringMethod: "" },
  retro: { cycleStart: "", cycleEnd: "", estimatedDurationDays: 0, wentWell: [], wentPoorly: [], processMetrics: {}, keyDecisions: [], learningEntries: [], nextCycleRecommendations: [] },
  guard: { previousMode: "NORMAL", newMode: "GUARD", activatedAt: "", blockedOperations: [], allowedOperations: [], deactivationCommand: "ds /careful" },
  careful: { previousMode: "NORMAL", newMode: "CAREFUL", activatedAt: "", gatedOperations: [], deactivationCommand: "" },
  learn: { entryId: "", topic: "", insight: "", originalText: "", wasRephrased: false, appliesTo: [], storedAt: "", learningStoreSize: 0 },
  "setup-memory": { updatedFields: [], addedDecisions: 0, addedDomainTerms: 0, importedFromRetro: false, memoryFilePath: "", previousMemoryHash: "", newMemoryHash: "" },
  "make-pdf": { title: "", artifactsIncluded: [], pageCount: 1, pdfPath: "", fileSizeKb: 1, generatedAt: "" },
  benchmark: { suiteName: "", model: "", runAt: "", results: [], summary: {} },
  "benchmark-models": { suiteName: "", modelsCompared: [], runAt: "", modelResults: [], recommendation: {} },
  skillify: { skillName: "", manifestPath: "", handlerPath: "", generatedModel: "", generatedTools: [], schemaValid: true, schemaValidationErrors: [], installInstructions: "", warnings: [] },
  codex: { sourceArtifact: "", taskExtracted: "", codexPrompt: "", codexCommand: "", codexOutput: "", codexExitCode: 0, codexVerdict: "NOT_INSTALLED", filesModified: [], warnings: [] },
  cso: { overallAssessment: "ON_TRACK", confidenceLevel: "HIGH", confidenceRationale: "", strategicStrengths: [], topThreeRisks: [], scopeAssessment: "", timelineRealism: "ON_TRACK", nextCycleRecommendations: [], artifactsReviewed: [], summary: "" },
  freeze: { frozen: true, frozenAt: "", reason: null, frozenUntil: null, unfreezeCommand: "ds /unfreeze" },
  unfreeze: { frozen: false, unfrozenAt: "", previousFreezeReason: null, previousFrozenSince: "" },
  canary: { environment: "staging", canaryPercent: 10, deployedAt: "", monitorDurationMinutes: 15, healthChecks: [], canaryVerdict: "PROMOTE", recommendation: "", rollbackExecuted: false },
  "dstack-upgrade": { currentVersion: "0.1.0", latestVersion: "0.1.0", isUpToDate: true, changelogSummary: "", breakingChanges: [], requiredMigrations: [], upgradeApproved: false, upgradeExecuted: false, postUpgradeVerification: "SKIPPED" },
  "plan-tune": { baseArtifactTimestamp: "", reviewsConsidered: [], issuesAddressed: [], issuesDeferred: [], changeLog: [], revisedPlan: {} }
};
