import { Router } from 'express';
import { ArtifactStore } from '@dstack/core';
import path from 'path';

export const artifactsRouter = Router();

const getDStackDir = () => path.join(process.cwd(), '.dstack');

artifactsRouter.get('/', async (req, res) => {
  try {
    const store = new ArtifactStore(getDStackDir());
    const skills = await store.listSkillsWithArtifacts();
    
    const results = [];
    for (const skill of skills) {
      const latest = await store.readLatest(skill);
      if (latest) {
        results.push({
          skillName: skill,
          verdict: latest.verdict,
          timestamp: latest.createdAt,
          path: latest.filePath,
          content: latest.content
        });
      }
    }
    res.json(results);
  } catch (err) {
    console.error('Failed to list artifacts:', err);
    res.status(500).json({ error: 'Failed to list artifacts' });
  }
});

artifactsRouter.get('/:skillName/latest', async (req, res) => {
  try {
    const store = new ArtifactStore(getDStackDir());
    const latest = await store.readLatest(req.params.skillName);
    if (!latest) {
      return res.status(404).json({ error: 'Artifact not found' });
    }
    res.json(latest);
  } catch (err) {
    console.error('Failed to get latest artifact:', err);
    res.status(500).json({ error: 'Failed to get latest artifact' });
  }
});

artifactsRouter.get('/:skillName', async (req, res) => {
  try {
    const store = new ArtifactStore(getDStackDir());
    const artifacts = await store.list(req.params.skillName);
    res.json(artifacts.map(a => ({
      id: a.id,
      timestamp: a.createdAt,
      verdict: a.verdict
    })));
  } catch (err) {
    console.error('Failed to get artifact history:', err);
    res.status(500).json({ error: 'Failed to get artifact history' });
  }
});
artifactsRouter.get('/:skillName/diff', async (req, res) => {
  try {
    const { v1, v2 } = req.query;
    if (!v1 || !v2) return res.status(400).json({ error: 'v1 and v2 required' });
    
    const store = new ArtifactStore(getDStackDir());
    const [oldArt, newArt] = await Promise.all([
      store.read(req.params.skillName, v1 as string),
      store.read(req.params.skillName, v2 as string)
    ]);
    
    if (!oldArt || !newArt) return res.status(404).json({ error: 'Version not found' });
    
    // Semantic summary mock (would be generated by LLM in real impl)
    const semanticSummary = newArt.verdict !== oldArt.verdict 
      ? `Verdict changed from ${oldArt.verdict} to ${newArt.verdict} due to new requirements.`
      : `Minor updates to field definitions without verdict change.`;

    res.json({
      v1: oldArt,
      v2: newArt,
      semanticSummary
    });
  } catch (err) {
    console.error('Failed to diff artifacts:', err);
    res.status(500).json({ error: 'Failed to diff artifacts' });
  }
});
